/**
 * Preset color schemes for the application.
 * Each preset defines CSS variable overrides for both dark and light modes.
 * Variables follow the Material Design 3 tonal palette approach.
 */

import * as colorUtils from './colorUtils';

export const SURFACE_COLOR_KEYS = [
  'surface-tint',
  'surface',
  'surface-dim',
  'surface-container-lowest',
  'surface-container-low',
  'surface-container',
  'surface-container-high',
  'surface-container-highest',
  'surface-bright',
  'surface-variant',
  'on-surface',
  'on-background',
  'on-surface-variant',
] as const;

// The CSS variable keys we override (without --color- prefix)
export const COLOR_KEYS = [
  ...SURFACE_COLOR_KEYS,
  'primary',
  'primary-container',
  'on-primary',
  'on-primary-container',
  'secondary',
  'secondary-container',
  'on-secondary',
  'on-secondary-container',
  'tertiary',
  'tertiary-container',
  'on-tertiary',
  'on-tertiary-container',
  'error',
  'error-container',
  'outline',
  'outline-variant',
] as const;

export type ColorKey = (typeof COLOR_KEYS)[number];
export type SurfaceColorKey = (typeof SURFACE_COLOR_KEYS)[number];

export interface ColorPreset {
  label: string;
  primary: string; // main accent color for display in UI picker
  dark: Record<ColorKey, string>;
  light: Record<ColorKey, string>;
}

type SurfacePalette = Record<SurfaceColorKey, string>;

function createSurfacePalette(hue: number, saturation: number): { dark: SurfacePalette; light: SurfacePalette } {
  const darkSat = Math.max(7, Math.round(saturation * 0.52));
  const darkVariantSat = Math.max(14, Math.round(saturation * 0.78));
  const lightSat = Math.max(10, Math.round(saturation * 0.45));
  const lightVariantSat = Math.max(18, Math.round(saturation * 0.66));

  return {
    dark: {
      'surface-tint': colorUtils.hslToHex(hue, Math.max(42, saturation), 72),
      surface: colorUtils.hslToHex(hue, darkSat, 8),
      'surface-dim': colorUtils.hslToHex(hue, darkSat, 7),
      'surface-container-lowest': colorUtils.hslToHex(hue, darkSat, 5),
      'surface-container-low': colorUtils.hslToHex(hue, darkSat, 11),
      'surface-container': colorUtils.hslToHex(hue, darkSat, 13),
      'surface-container-high': colorUtils.hslToHex(hue, darkSat, 17),
      'surface-container-highest': colorUtils.hslToHex(hue, darkSat, 21),
      'surface-bright': colorUtils.hslToHex(hue, darkSat, 24),
      'surface-variant': colorUtils.hslToHex(hue, darkVariantSat, 21),
      'on-surface': colorUtils.hslToHex(hue, 8, 90),
      'on-background': colorUtils.hslToHex(hue, 8, 90),
      'on-surface-variant': colorUtils.hslToHex(hue, darkVariantSat, 79),
    },
    light: {
      'surface-tint': colorUtils.hslToHex(hue, Math.max(42, saturation), 42),
      surface: colorUtils.hslToHex(hue, lightSat, 98),
      'surface-dim': colorUtils.hslToHex(hue, lightSat, 92),
      'surface-container-lowest': '#ffffff',
      'surface-container-low': colorUtils.hslToHex(hue, lightSat, 96),
      'surface-container': colorUtils.hslToHex(hue, lightSat, 94),
      'surface-container-high': colorUtils.hslToHex(hue, lightSat, 91),
      'surface-container-highest': colorUtils.hslToHex(hue, lightSat, 88),
      'surface-bright': colorUtils.hslToHex(hue, lightSat, 98),
      'surface-variant': colorUtils.hslToHex(hue, lightVariantSat, 88),
      'on-surface': colorUtils.hslToHex(hue, 12, 12),
      'on-background': colorUtils.hslToHex(hue, 12, 12),
      'on-surface-variant': colorUtils.hslToHex(hue, lightVariantSat, 28),
    },
  };
}

const orangeSurface = createSurfacePalette(28, 34);
const blueSurface = createSurfacePalette(218, 30);
const greenSurface = createSurfacePalette(154, 29);
const purpleSurface = createSurfacePalette(266, 28);
const redSurface = createSurfacePalette(4, 34);
const tealSurface = createSurfacePalette(176, 28);

export const COLOR_PRESETS: Record<string, ColorPreset> = {
  orange: {
    label: '橙色',
    primary: '#f97316',
    dark: {
      ...orangeSurface.dark,
      primary: '#ffb690',
      'primary-container': '#f97316',
      'on-primary': '#552100',
      'on-primary-container': '#582200',
      secondary: '#b7c8e1',
      'secondary-container': '#3a4a5f',
      'on-secondary': '#213145',
      'on-secondary-container': '#a9bad3',
      tertiary: '#93ccff',
      'tertiary-container': '#00a2f4',
      'on-tertiary': '#003351',
      'on-tertiary-container': '#003554',
      error: '#ffb4ab',
      'error-container': '#93000a',
      outline: '#a78b7d',
      'outline-variant': '#584237',
    },
    light: {
      ...orangeSurface.light,
      primary: '#8f5a30',
      'primary-container': '#f97316',
      'on-primary': '#ffffff',
      'on-primary-container': '#3a1c00',
      secondary: '#4a6280',
      'secondary-container': '#d3e4ff',
      'on-secondary': '#1a3048',
      'on-secondary-container': '#1a3048',
      tertiary: '#006494',
      'tertiary-container': '#c8e6ff',
      'on-tertiary': '#003554',
      'on-tertiary-container': '#003554',
      error: '#ba1a1a',
      'error-container': '#ffdad6',
      outline: '#7e756b',
      'outline-variant': '#d4c4b7',
    },
  },
  blue: {
    label: '蓝色',
    primary: '#3b82f6',
    dark: {
      ...blueSurface.dark,
      primary: '#aac7ff',
      'primary-container': '#3b82f6',
      'on-primary': '#002e5c',
      'on-primary-container': '#003d7a',
      secondary: '#bec6dc',
      'secondary-container': '#3e4759',
      'on-secondary': '#283042',
      'on-secondary-container': '#a9b1c7',
      tertiary: '#dbbce4',
      'tertiary-container': '#6b4276',
      'on-tertiary': '#3e1d49',
      'on-tertiary-container': '#c49ace',
      error: '#ffb4ab',
      'error-container': '#93000a',
      outline: '#8e9099',
      'outline-variant': '#44474f',
    },
    light: {
      ...blueSurface.light,
      primary: '#2b5ea7',
      'primary-container': '#3b82f6',
      'on-primary': '#ffffff',
      'on-primary-container': '#001b3e',
      secondary: '#565e71',
      'secondary-container': '#dbe2f9',
      'on-secondary': '#131c2e',
      'on-secondary-container': '#131c2e',
      tertiary: '#6b4276',
      'tertiary-container': '#f5d9ff',
      'on-tertiary': '#3e1d49',
      'on-tertiary-container': '#3e1d49',
      error: '#ba1a1a',
      'error-container': '#ffdad6',
      outline: '#757780',
      'outline-variant': '#c5c6d0',
    },
  },
  green: {
    label: '绿色',
    primary: '#10b981',
    dark: {
      ...greenSurface.dark,
      primary: '#6ee7b7',
      'primary-container': '#10b981',
      'on-primary': '#003823',
      'on-primary-container': '#005236',
      secondary: '#b2ccc2',
      'secondary-container': '#354b41',
      'on-secondary': '#1e352c',
      'on-secondary-container': '#9db7ad',
      tertiary: '#a8ced8',
      'tertiary-container': '#355760',
      'on-tertiary': '#0d1f24',
      'on-tertiary-container': '#92b8c2',
      error: '#ffb4ab',
      'error-container': '#93000a',
      outline: '#859389',
      'outline-variant': '#3b4b40',
    },
    light: {
      ...greenSurface.light,
      primary: '#1a6b47',
      'primary-container': '#10b981',
      'on-primary': '#ffffff',
      'on-primary-container': '#002114',
      secondary: '#405650',
      'secondary-container': '#c2e9d5',
      'on-secondary': '#0d1f17',
      'on-secondary-container': '#0d1f17',
      tertiary: '#355760',
      'tertiary-container': '#c1ecf5',
      'on-tertiary': '#0d1f24',
      'on-tertiary-container': '#0d1f24',
      error: '#ba1a1a',
      'error-container': '#ffdad6',
      outline: '#6f7d73',
      'outline-variant': '#bfc9c1',
    },
  },
  purple: {
    label: '紫色',
    primary: '#8b5cf6',
    dark: {
      ...purpleSurface.dark,
      primary: '#cfbcff',
      'primary-container': '#8b5cf6',
      'on-primary': '#381e72',
      'on-primary-container': '#4f378b',
      secondary: '#ccc2dc',
      'secondary-container': '#4a4458',
      'on-secondary': '#332d41',
      'on-secondary-container': '#b6adc4',
      tertiary: '#efb8c8',
      'tertiary-container': '#8b5a6e',
      'on-tertiary': '#4a2536',
      'on-tertiary-container': '#d89caa',
      error: '#ffb4ab',
      'error-container': '#93000a',
      outline: '#938f99',
      'outline-variant': '#49454f',
    },
    light: {
      ...purpleSurface.light,
      primary: '#6750a4',
      'primary-container': '#8b5cf6',
      'on-primary': '#ffffff',
      'on-primary-container': '#21005d',
      secondary: '#625b71',
      'secondary-container': '#e8def8',
      'on-secondary': '#1d192b',
      'on-secondary-container': '#1d192b',
      tertiary: '#7d5260',
      'tertiary-container': '#ffd8e4',
      'on-tertiary': '#31111d',
      'on-tertiary-container': '#31111d',
      error: '#ba1a1a',
      'error-container': '#ffdad6',
      outline: '#79747e',
      'outline-variant': '#cac4d0',
    },
  },
  red: {
    label: '红色',
    primary: '#ef4444',
    dark: {
      ...redSurface.dark,
      primary: '#ffb4ab',
      'primary-container': '#ef4444',
      'on-primary': '#690005',
      'on-primary-container': '#8c0009',
      secondary: '#e7bdc0',
      'secondary-container': '#6e4c50',
      'on-secondary': '#44292d',
      'on-secondary-container': '#cba4a8',
      tertiary: '#f0c4a3',
      'tertiary-container': '#7a5900',
      'on-tertiary': '#452b00',
      'on-tertiary-container': '#d4a87c',
      error: '#ffb4ab',
      'error-container': '#93000a',
      outline: '#a08580',
      'outline-variant': '#5c3f3c',
    },
    light: {
      ...redSurface.light,
      primary: '#a33b3b',
      'primary-container': '#ef4444',
      'on-primary': '#ffffff',
      'on-primary-container': '#3b0808',
      secondary: '#77565a',
      'secondary-container': '#ffdada',
      'on-secondary': '#2c1518',
      'on-secondary-container': '#2c1518',
      tertiary: '#7a5900',
      'tertiary-container': '#ffe0c0',
      'on-tertiary': '#271800',
      'on-tertiary-container': '#271800',
      error: '#ba1a1a',
      'error-container': '#ffdad6',
      outline: '#856366',
      'outline-variant': '#d8c0bc',
    },
  },
  teal: {
    label: '青色',
    primary: '#14b8a6',
    dark: {
      ...tealSurface.dark,
      primary: '#5eead4',
      'primary-container': '#14b8a6',
      'on-primary': '#003731',
      'on-primary-container': '#005048',
      secondary: '#b0ccc8',
      'secondary-container': '#374946',
      'on-secondary': '#1c3330',
      'on-secondary-container': '#9ab8b3',
      tertiary: '#b5c5e8',
      'tertiary-container': '#3c4f6e',
      'on-tertiary': '#152233',
      'on-tertiary-container': '#9faed1',
      error: '#ffb4ab',
      'error-container': '#93000a',
      outline: '#7e9994',
      'outline-variant': '#3e524e',
    },
    light: {
      ...tealSurface.light,
      primary: '#1a6b5e',
      'primary-container': '#14b8a6',
      'on-primary': '#ffffff',
      'on-primary-container': '#00201c',
      secondary: '#4a6360',
      'secondary-container': '#cce8e3',
      'on-secondary': '#0d1f1d',
      'on-secondary-container': '#0d1f1d',
      tertiary: '#3c4f6e',
      'tertiary-container': '#d6e4f7',
      'on-tertiary': '#152233',
      'on-tertiary-container': '#152233',
      error: '#ba1a1a',
      'error-container': '#ffdad6',
      outline: '#6f807c',
      'outline-variant': '#b8ceca',
    },
  },
};
