/**
 * Preset color schemes for the application.
 * Each preset defines CSS variable overrides for both dark and light modes.
 * Variables follow the Material Design 3 tonal palette approach.
 */

export interface ColorPreset {
  label: string;
  primary: string; // main accent color for display in UI picker
  dark: Record<string, string>;
  light: Record<string, string>;
}

// The CSS variable keys we override (without --color- prefix)
export const COLOR_KEYS = [
  'primary', 'primary-container', 'on-primary', 'on-primary-container',
  'secondary', 'secondary-container', 'on-secondary', 'on-secondary-container',
  'tertiary', 'tertiary-container', 'on-tertiary', 'on-tertiary-container',
  'error', 'error-container',
  'outline', 'outline-variant',
  'on-surface-variant',
] as const;

export type ColorKey = typeof COLOR_KEYS[number];

export const COLOR_PRESETS: Record<string, ColorPreset> = {
  orange: {
    label: '橙色',
    primary: '#f97316',
    dark: {
      'primary': '#ffb690',
      'primary-container': '#f97316',
      'on-primary': '#552100',
      'on-primary-container': '#582200',
      'secondary': '#b7c8e1',
      'secondary-container': '#3a4a5f',
      'on-secondary': '#213145',
      'on-secondary-container': '#a9bad3',
      'tertiary': '#93ccff',
      'tertiary-container': '#00a2f4',
      'on-tertiary': '#003351',
      'on-tertiary-container': '#003554',
      'error': '#ffb4ab',
      'error-container': '#93000a',
      'outline': '#a78b7d',
      'outline-variant': '#584237',
      'on-surface-variant': '#e0c0b1',
    },
    light: {
      'primary': '#8f5a30',
      'primary-container': '#f97316',
      'on-primary': '#ffffff',
      'on-primary-container': '#3a1c00',
      'secondary': '#4a6280',
      'secondary-container': '#d3e4ff',
      'on-secondary': '#1a3048',
      'on-secondary-container': '#1a3048',
      'tertiary': '#006494',
      'tertiary-container': '#c8e6ff',
      'on-tertiary': '#003554',
      'on-tertiary-container': '#003554',
      'error': '#ba1a1a',
      'error-container': '#ffdad6',
      'outline': '#7e756b',
      'outline-variant': '#d4c4b7',
      'on-surface-variant': '#4e4539',
    },
  },
  blue: {
    label: '蓝色',
    primary: '#3b82f6',
    dark: {
      'primary': '#aac7ff',
      'primary-container': '#3b82f6',
      'on-primary': '#002e5c',
      'on-primary-container': '#003d7a',
      'secondary': '#bec6dc',
      'secondary-container': '#3e4759',
      'on-secondary': '#283042',
      'on-secondary-container': '#a9b1c7',
      'tertiary': '#dbbce4',
      'tertiary-container': '#6b4276',
      'on-tertiary': '#3e1d49',
      'on-tertiary-container': '#c49ace',
      'error': '#ffb4ab',
      'error-container': '#93000a',
      'outline': '#8e9099',
      'outline-variant': '#44474f',
      'on-surface-variant': '#c4c6d0',
    },
    light: {
      'primary': '#2b5ea7',
      'primary-container': '#3b82f6',
      'on-primary': '#ffffff',
      'on-primary-container': '#001b3e',
      'secondary': '#565e71',
      'secondary-container': '#dbe2f9',
      'on-secondary': '#131c2e',
      'on-secondary-container': '#131c2e',
      'tertiary': '#6b4276',
      'tertiary-container': '#f5d9ff',
      'on-tertiary': '#3e1d49',
      'on-tertiary-container': '#3e1d49',
      'error': '#ba1a1a',
      'error-container': '#ffdad6',
      'outline': '#757780',
      'outline-variant': '#c5c6d0',
      'on-surface-variant': '#434750',
    },
  },
  green: {
    label: '绿色',
    primary: '#10b981',
    dark: {
      'primary': '#6ee7b7',
      'primary-container': '#10b981',
      'on-primary': '#003823',
      'on-primary-container': '#005236',
      'secondary': '#b2ccc2',
      'secondary-container': '#354b41',
      'on-secondary': '#1e352c',
      'on-secondary-container': '#9db7ad',
      'tertiary': '#a8ced8',
      'tertiary-container': '#355760',
      'on-tertiary': '#0d1f24',
      'on-tertiary-container': '#92b8c2',
      'error': '#ffb4ab',
      'error-container': '#93000a',
      'outline': '#859389',
      'outline-variant': '#3b4b40',
      'on-surface-variant': '#bfc9c1',
    },
    light: {
      'primary': '#1a6b47',
      'primary-container': '#10b981',
      'on-primary': '#ffffff',
      'on-primary-container': '#002114',
      'secondary': '#405650',
      'secondary-container': '#c2e9d5',
      'on-secondary': '#0d1f17',
      'on-secondary-container': '#0d1f17',
      'tertiary': '#355760',
      'tertiary-container': '#c1ecf5',
      'on-tertiary': '#0d1f24',
      'on-tertiary-container': '#0d1f24',
      'error': '#ba1a1a',
      'error-container': '#ffdad6',
      'outline': '#6f7d73',
      'outline-variant': '#bfc9c1',
      'on-surface-variant': '#3d4b42',
    },
  },
  purple: {
    label: '紫色',
    primary: '#8b5cf6',
    dark: {
      'primary': '#cfbcff',
      'primary-container': '#8b5cf6',
      'on-primary': '#381e72',
      'on-primary-container': '#4f378b',
      'secondary': '#ccc2dc',
      'secondary-container': '#4a4458',
      'on-secondary': '#332d41',
      'on-secondary-container': '#b6adc4',
      'tertiary': '#efb8c8',
      'tertiary-container': '#8b5a6e',
      'on-tertiary': '#4a2536',
      'on-tertiary-container': '#d89caa',
      'error': '#ffb4ab',
      'error-container': '#93000a',
      'outline': '#938f99',
      'outline-variant': '#49454f',
      'on-surface-variant': '#cac4d0',
    },
    light: {
      'primary': '#6750a4',
      'primary-container': '#8b5cf6',
      'on-primary': '#ffffff',
      'on-primary-container': '#21005d',
      'secondary': '#625b71',
      'secondary-container': '#e8def8',
      'on-secondary': '#1d192b',
      'on-secondary-container': '#1d192b',
      'tertiary': '#7d5260',
      'tertiary-container': '#ffd8e4',
      'on-tertiary': '#31111d',
      'on-tertiary-container': '#31111d',
      'error': '#ba1a1a',
      'error-container': '#ffdad6',
      'outline': '#79747e',
      'outline-variant': '#cac4d0',
      'on-surface-variant': '#49454f',
    },
  },
  red: {
    label: '红色',
    primary: '#ef4444',
    dark: {
      'primary': '#ffb4ab',
      'primary-container': '#ef4444',
      'on-primary': '#690005',
      'on-primary-container': '#8c0009',
      'secondary': '#e7bdc0',
      'secondary-container': '#6e4c50',
      'on-secondary': '#44292d',
      'on-secondary-container': '#cba4a8',
      'tertiary': '#f0c4a3',
      'tertiary-container': '#7a5900',
      'on-tertiary': '#452b00',
      'on-tertiary-container': '#d4a87c',
      'error': '#ffb4ab',
      'error-container': '#93000a',
      'outline': '#a08580',
      'outline-variant': '#5c3f3c',
      'on-surface-variant': '#e8bdb8',
    },
    light: {
      'primary': '#a33b3b',
      'primary-container': '#ef4444',
      'on-primary': '#ffffff',
      'on-primary-container': '#3b0808',
      'secondary': '#77565a',
      'secondary-container': '#ffdada',
      'on-secondary': '#2c1518',
      'on-secondary-container': '#2c1518',
      'tertiary': '#7a5900',
      'tertiary-container': '#ffe0c0',
      'on-tertiary': '#271800',
      'on-tertiary-container': '#271800',
      'error': '#ba1a1a',
      'error-container': '#ffdad6',
      'outline': '#856366',
      'outline-variant': '#d8c0bc',
      'on-surface-variant': '#534341',
    },
  },
  teal: {
    label: '青色',
    primary: '#14b8a6',
    dark: {
      'primary': '#5eead4',
      'primary-container': '#14b8a6',
      'on-primary': '#003731',
      'on-primary-container': '#005048',
      'secondary': '#b0ccc8',
      'secondary-container': '#374946',
      'on-secondary': '#1c3330',
      'on-secondary-container': '#9ab8b3',
      'tertiary': '#b5c5e8',
      'tertiary-container': '#3c4f6e',
      'on-tertiary': '#152233',
      'on-tertiary-container': '#9faed1',
      'error': '#ffb4ab',
      'error-container': '#93000a',
      'outline': '#7e9994',
      'outline-variant': '#3e524e',
      'on-surface-variant': '#b8ceca',
    },
    light: {
      'primary': '#1a6b5e',
      'primary-container': '#14b8a6',
      'on-primary': '#ffffff',
      'on-primary-container': '#00201c',
      'secondary': '#4a6360',
      'secondary-container': '#cce8e3',
      'on-secondary': '#0d1f1d',
      'on-secondary-container': '#0d1f1d',
      'tertiary': '#3c4f6e',
      'tertiary-container': '#d6e4f7',
      'on-tertiary': '#152233',
      'on-tertiary-container': '#152233',
      'error': '#ba1a1a',
      'error-container': '#ffdad6',
      'outline': '#6f807c',
      'outline-variant': '#b8ceca',
      'on-surface-variant': '#3f524e',
    },
  },
};
