import { execSync } from "child_process";
import { readFileSync, writeFileSync, unlinkSync } from "node:fs";
import { join } from "node:path";
import { syncJob, loadJob } from "./jobStore.js";

interface UpdateJob {
  id: string;
  stage: "pulling" | "building" | "restarting" | "done" | "error";
  percent: number;
  message: string;
  error?: string;
  logs: string[];
}

const jobs = new Map<string, UpdateJob>();
let isRunning = false;

/**
 * Auto-detect host project directory via Docker API.
 */
function detectHostProjectDir(): string | null {
  try {
    const containerId = readFileSync("/etc/hostname", "utf-8").trim();
    const result = execSync(
      `curl -sf --unix-socket /var/run/docker.sock "http://localhost/containers/${containerId}/json"`,
      { encoding: "utf-8", timeout: 5000, stdio: ["pipe", "pipe", "pipe"] },
    );
    const info = JSON.parse(result);
    const mounts: Array<{ Destination: string; Source: string }> = info.Mounts || [];
    const projectMount = mounts.find((m) => m.Destination === "/project");
    return projectMount?.Source || null;
  } catch {
    return null;
  }
}

/**
 * Generate docker-compose.override.yml with absolute host paths.
 * When using -f, docker-compose does NOT auto-load override files,
 * so we must explicitly pass both -f flags.
 */
function writeOverrideCompose(projectDir: string, hostProjectDir: string): string {
  const overridePath = join(projectDir, "docker-compose.override.yml");
  const override = `# Auto-generated by update system — DO NOT EDIT
services:
  api:
    volumes:
      - uploads-data:/app/uploads
      - ${hostProjectDir}/server/static:/app/static
      - /var/run/docker.sock:/var/run/docker.sock
      - ${hostProjectDir}:/project:rw
`;
  writeFileSync(overridePath, override, "utf-8");
  return overridePath;
}

export function getUpdateJob(id: string): UpdateJob | undefined {
  return jobs.get(id) || loadJob<UpdateJob>(id);
}

function addLog(job: UpdateJob, text: string) {
  const time = new Date().toLocaleTimeString("zh-CN", { hour12: false });
  job.logs.push(`[${time}] ${text}`);
  console.log(`[Update #${job.id}] ${text}`);
  syncJob(job);
}

export function checkUpdateAvailable(): { current: string; remote: string; updateAvailable: boolean; warning?: string } {
  const projectDir = "/project";
  const defaultResult = { current: "unknown", remote: "unknown", updateAvailable: false, warning: undefined as string | undefined };

  try {
    execSync("git rev-parse --git-dir", { cwd: projectDir, encoding: "utf-8", timeout: 3000, stdio: "pipe" });
  } catch {
    defaultResult.warning = "当前环境不支持自动更新（缺少项目目录或 Git）";
    return defaultResult;
  }

  const hostDir = detectHostProjectDir();
  if (!hostDir) {
    defaultResult.warning = "无法自动检测宿主机项目路径，请确保容器挂载了 Docker Socket 和项目目录";
  }

  try {
    // Fetch tags to ensure version display is accurate
    try {
      execSync("git fetch origin --tags", { cwd: projectDir, encoding: "utf-8", timeout: 30000, stdio: "pipe" });
    } catch { /* non-critical */ }

    // Version display from git tag (e.g., "v1.2.0"), fallback to hash
    let currentTag: string;
    try {
      currentTag = execSync("git describe --tags --abbrev=0", { cwd: projectDir, encoding: "utf-8" }).trim();
    } catch {
      currentTag = execSync("git rev-parse --short HEAD", { cwd: projectDir, encoding: "utf-8" }).trim();
    }

    const currentHash = execSync("git rev-parse HEAD", { cwd: projectDir, encoding: "utf-8" }).trim();

    let remoteTag = "unknown";
    let remoteHash = "unknown";
    try {
      execSync("git fetch origin main --tags", { cwd: projectDir, encoding: "utf-8", timeout: 30000, stdio: "pipe" });
      remoteHash = execSync("git rev-parse origin/main", { cwd: projectDir, encoding: "utf-8" }).trim();
      try {
        remoteTag = execSync("git describe --tags --abbrev=0 origin/main", { cwd: projectDir, encoding: "utf-8" }).trim();
      } catch {
        remoteTag = execSync("git rev-parse --short origin/main", { cwd: projectDir, encoding: "utf-8" }).trim();
      }
    } catch {
      // fetch failed
    }

    // Update available if commit hashes differ (works even without new tags)
    const updateAvailable = currentHash !== remoteHash && remoteHash !== "unknown";
    return { current: currentTag, remote: remoteTag, updateAvailable, warning: defaultResult.warning };
  } catch {
    return defaultResult;
  }
}

export function startUpdateJob(): string {
  if (isRunning) {
    throw new Error("已有更新任务正在执行");
  }
  const id = `update_${Date.now()}`;
  const job: UpdateJob = { id, stage: "pulling", percent: 0, message: "正在拉取最新代码...", logs: [] };
  jobs.set(id, job);
  syncJob(job);
  isRunning = true;

  runUpdate(job).catch((err) => {
    job.stage = "error";
    job.error = err instanceof Error ? err.message : String(err);
    syncJob(job);
    console.error(`[Update #${job.id}] Error:`, job.error);
  }).finally(() => {
    isRunning = false;
  });

  return id;
}

async function runUpdate(job: UpdateJob) {
  const projectDir = "/project";
  const composeFile = "docker-compose.prod.yml";

  const hostProjectDir = detectHostProjectDir();
  if (!hostProjectDir) {
    throw new Error("无法检测宿主机项目路径，请确保容器正确挂载了 Docker Socket 和项目目录");
  }
  console.log(`[Update] Host project dir detected: ${hostProjectDir}`);
  addLog(job, `检测到宿主机路径: ${hostProjectDir}`);

  // Step 1: Pull latest code (0-30%)
  job.stage = "pulling";
  job.percent = 5;
  job.message = "正在拉取最新代码...";
  addLog(job, "开始从 GitHub 拉取最新代码...");

  try {
    addLog(job, "执行 git fetch origin main...");
    execSync("git fetch origin main --tags", { cwd: projectDir, encoding: "utf-8", timeout: 120000, stdio: "pipe" });
    job.percent = 15;
    job.message = "正在合并代码...";
    syncJob(job);
    addLog(job, "拉取成功，开始合并代码...");
    execSync("git reset --hard origin/main", { cwd: projectDir, encoding: "utf-8", timeout: 60000, stdio: "pipe" });
    const newHash = execSync("git rev-parse --short HEAD", { cwd: projectDir, encoding: "utf-8" }).trim();
    job.percent = 30;
    job.message = "代码已更新";
    syncJob(job);
    addLog(job, `代码合并成功，当前版本: ${newHash}`);
  } catch (err: any) {
    addLog(job, `拉取代码失败: ${err.message}`);
    throw new Error(`拉取代码失败: ${err.message}`);
  }

  // Write override compose file
  let overridePath: string | undefined;
  try {
    overridePath = writeOverrideCompose(projectDir, hostProjectDir);
    addLog(job, "生成更新配置文件成功");
  } catch (err: any) {
    addLog(job, `生成配置失败: ${err.message}`);
    throw new Error(`生成更新配置失败: ${err.message}`);
  }

  const composeCmd = `docker-compose -f ${composeFile} -f docker-compose.override.yml`;

  try {
    // Step 2: Build new images (30-80%)
    job.stage = "building";
    job.percent = 35;
    job.message = "正在构建 API 服务...";
    syncJob(job);
    addLog(job, "开始构建 API 服务镜像（可能需要几分钟）...");

    execSync(`${composeCmd} build api`, {
      cwd: projectDir, encoding: "utf-8", timeout: 600000, stdio: "pipe",
    });
    job.percent = 60;
    job.message = "正在构建前端服务...";
    syncJob(job);
    addLog(job, "API 服务构建完成，开始构建前端...");

    execSync(`${composeCmd} build web`, {
      cwd: projectDir, encoding: "utf-8", timeout: 600000, stdio: "pipe",
    });
    job.percent = 80;
    job.message = "构建完成";
    syncJob(job);
    addLog(job, "前端服务构建完成");

    // Step 3: Restart services (80-100%)
    job.stage = "restarting";
    job.percent = 85;
    job.message = "正在重启服务（连接即将断开）...";
    syncJob(job);
    addLog(job, "开始重启服务，连接即将断开...");

    execSync(`${composeCmd} up -d`, {
      cwd: projectDir, encoding: "utf-8", timeout: 120000, stdio: "pipe",
    });
    job.percent = 100;
    job.message = "更新完成";
    job.stage = "done";
    syncJob(job);
    addLog(job, "更新完成！服务已重启");
  } catch (err: any) {
    addLog(job, `构建/重启失败: ${err.message}`);
    try { if (overridePath) unlinkSync(overridePath); } catch {}
    throw new Error(`构建/重启失败: ${err.message}`);
  }

  try { if (overridePath) unlinkSync(overridePath); } catch {}
}
